import { DEFAULT_AVATAR, PARAMETERS } from '../avatar/parameters';
import { FABRICS, GARMENTS, SWATCHES } from '../garments/catalog';
import { garmentIcon, icon } from './icons';
export function renderLayout() {
  document.querySelector<HTMLDivElement>('#app')!.innerHTML = `
  <header class="app-header"><a class="brand" href="./" aria-label="Garment Playground home"><span class="brand-mark">${icon('sliders',23)}</span><span>Garment Playground<span class="brand-caption">A SYNTHETIC WARDROBE LAB</span></span></a><div class="header-actions"><span class="local-badge"><i></i> Local only</span><button id="about" class="quiet-button">${icon('info')}<span>About this sandbox</span></button></div></header>
  <main>
    <section class="page-heading"><div><div class="eyebrow">THE STUDIO <span>/</span> EXPERIMENT 001</div><h1>A little room to experiment.</h1><p>Shape an avatar. Explore a silhouette. See what changes.</p></div><button id="save-setup" class="outline-button">${icon('download')} Save setup</button></section>
    <div class="evidence-strip" aria-label="Prototype capabilities"><span class="evidence active"><b>01</b> Visual placement <i>AVAILABLE</i></span><span class="evidence"><b>02</b> Animated behavior <i>SKINNING ONLY</i></span><span class="evidence unavailable"><b>03</b> Validated drape <i>UNAVAILABLE</i></span></div>
    <div class="workspace">
      <aside class="panel avatar-panel"><div class="panel-title"><h2>${icon('sliders',16)} Synthetic human</h2><button id="reset-avatar" class="icon-button" aria-label="Reset avatar" title="Reset avatar">${icon('reset',16)}</button></div>
      <p class="panel-note">Synthetic avatar parameters,<br>not body measurements.</p>
      <div class="parameter-list">${PARAMETERS.map(p => `<div class="parameter"><label for="avatar-${p.key}">${p.label}</label><output for="avatar-${p.key}" id="value-${p.key}">${DEFAULT_AVATAR[p.key].toFixed(2)}${p.unit ? ' <span>m</span>' : ''}</output><input id="avatar-${p.key}" data-parameter="${p.key}" type="range" min="${p.min}" max="${p.max}" step="${p.step}" value="${DEFAULT_AVATAR[p.key]}" />${p.key === 'composition' ? '<div class="range-labels"><span>Defined</span><span>Softer</span></div>' : ''}</div>`).join('')}</div>
      <div class="avatar-footnote"><span class="small-dot"></span><div>Procedural human · neutral A-pose<br><span>Dimension inputs in meters (m)</span></div></div>
      <button id="asset-info" class="text-button">Asset details & provenance ${icon('arrow',14)}</button>
      </aside>
      <section class="center-column" aria-label="Garment preview">
        <div class="viewport" id="viewport"><div class="viewport-top"><span class="viewport-title"><span class="small-dot"></span> LIVE PREVIEW</span><span class="proxy-badge">VISUAL PROXY</span></div>
          <div class="viewport-meta"><b id="preview-name">Fitted T-shirt</b><span id="pose-label">Synthetic avatar / A-pose</span></div>
          <div class="viewport-tools"><button id="wireframe" class="tool-button" aria-label="Toggle wireframe" aria-pressed="false" title="Wireframe">${icon('grid')}</button><button id="reset-camera" class="tool-button" aria-label="Reset camera" title="Reset camera">${icon('reset')}</button><span class="tool-divider"></span><button id="zoom-in" class="tool-button" aria-label="Zoom in" title="Zoom in">${icon('plus')}</button><button id="zoom-out" class="tool-button" aria-label="Zoom out" title="Zoom out">${icon('minus')}</button></div>
          <div class="scale-label"><span id="height-label">1.76</span> m <small>input height</small></div>
          <div class="viewport-bottom"><div class="view-switcher" aria-label="Camera views"><button data-view="front">Front</button><button data-view="side">Side</button><button data-view="back">Back</button></div><button id="animate" class="motion-button" aria-pressed="false">${icon('play',14)} Preview motion</button></div>
        </div>
        <div class="viewport-caption"><span>${icon('orbit',14)} Drag to orbit <span class="caption-dot">·</span> Scroll to zoom</span><span>1 unit = 1 meter</span></div>
        <div class="wardrobe-heading"><h2>The proxy wardrobe</h2><span>6 synthetic assets</span></div>
        <div class="garment-grid" role="group" aria-label="Choose a garment">${GARMENTS.map((g,i) => `<button class="garment-card ${i === 0 ? 'selected' : ''}" data-garment="${g.id}" aria-pressed="${i===0}"><span class="garment-art" style="color:${g.color}">${garmentIcon(g.id)}<span class="selection-check">${icon('check',11)}</span></span><strong>${g.name}</strong><small>visual proxy</small></button>`).join('')}</div>
      </section>
      <aside class="panel garment-panel"><div class="panel-title"><h2>Garment settings</h2><span class="asset-number" id="asset-number">01 / 06</span></div><div class="selected-garment"><span class="selected-art" id="selected-art">${garmentIcon('fitted-tee')}</span><div><h3 id="garment-name">Fitted T-shirt</h3><p id="garment-detail">Close silhouette</p><span class="mini-tag">visual proxy</span></div></div>
        <div class="parameter"><label for="garment-size">Size scale</label><output id="size-value" for="garment-size">100 <span>%</span></output><input id="garment-size" type="range" min=".78" max="1.25" step=".01" value="1"><div class="range-labels"><span>Smaller</span><span>Larger</span></div></div>
        <div class="parameter"><label for="garment-ease">Added radial ease</label><output id="ease-value" for="garment-ease">0.020 <span>m</span></output><input id="garment-ease" type="range" min="0" max=".10" step=".005" value=".02"><div class="range-labels"><span>Close</span><span>Relaxed</span></div></div>
        <div class="color-control"><label for="garment-color">Color <span id="color-value">#657C68</span></label><div class="swatches">${SWATCHES.map(c=>`<button class="swatch" data-color="${c}" aria-label="Color ${c}" aria-pressed="${c === '#657c68'}" style="--swatch:${c}"></button>`).join('')}<label class="custom-color" title="Custom garment color"><input id="garment-color" type="color" value="#657c68" aria-label="Custom garment color">${icon('plus',14)}</label></div></div>
        <div class="fabric-control"><label for="fabric">Fabric appearance</label><select id="fabric">${Object.entries(FABRICS).map(([id,f])=>`<option value="${id}">${f.label}</option>`).join('')}</select><p>Surface preset only. No fabric physics.</p></div>
        <button id="reset-garment" class="reset-garment">${icon('reset',14)} Reset garment</button>
        <div class="diagnostic-panel"><div class="diagnostic-heading"><h3>Rendering diagnostics</h3>${icon('info',15)}</div><div class="diagnostic-status" id="diagnostic-status" role="status"><span class="status-dot"></span><strong id="status-text">Checking geometry…</strong></div><div class="diagnostic-metrics"><span>Intersecting samples</span><b id="collision-count">—</b><span>Max. edge extension</span><b id="extension-value">—</b></div><label class="toggle-row" for="diagnostic-toggle"><span>Show intersections</span><input id="diagnostic-toggle" type="checkbox" role="switch"><span class="switch-track"></span></label><p>Sampled geometry checks can miss intersections. Extension is a geometry proxy, not fabric strain.</p><p class="motion-note" id="motion-note" hidden>Live pose checks update ~3 times/sec.</p></div>
      </aside>
    </div>
    <footer class="disclaimer">${icon('info',15)}<p>A visual sandbox, never a fit prediction. No real-world size, pressure, comfort, or tailoring accuracy. <strong>No physically validated drape.</strong></p><span>BUILT TO EXPLORE</span></footer>
  </main>
  <dialog id="info-dialog"><div class="dialog-heading"><span class="eyebrow">LOCAL STUDIO / ASSET NOTES</span><button id="close-dialog" class="icon-button" aria-label="Close asset details">×</button></div><h2>Synthetic, by design.</h2><p>Every body and garment is generated in this browser. There are no captures, personal inputs, model weights, external fonts, analytics, or uploads.</p><div class="tier-notes"><p><b>01 · Visual placement</b>Procedural garment meshes with size and ease controls. All six are visual proxies.</p><p><b>02 · Animated behavior</b>Body and garments share a skeleton with their own skin weights. Motion is skeletal deformation, not physical cloth simulation.</p><p><b>03 · Physically validated drape</b>Unavailable. No verified patterns, real size specifications, fabric data, or validation results.</p></div><h3>Asset manifest</h3><div id="manifest-details"></div><p class="dialog-footnote">Body topology uses overlapping closed components in one skinned mesh. Garments use open shells with overlapping seams. Hair and accessory asset slots are separate and empty. No garment self-collision test is implemented.</p><button id="download-manifests" class="outline-button">${icon('download')} Save asset manifests</button></dialog>`;
}
